package com.yupay.lunatico.fxmview;

import javafx.beans.property.*;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * The Items in the store.
 *
 * @author InfoYupay SACS
 * @version 1.0
 */
public class FxItem {
    /**
     * The ID (autogenerated).
     */
    private final LongProperty id =
            new SimpleLongProperty(this, "id");
    /**
     * Description of the item.
     */
    private final StringProperty description =
            new SimpleStringProperty(this, "description");
    /**
     * Measurement unit.
     */
    private final ObjectProperty<FxUnit> unit =
            new SimpleObjectProperty<>(this, "unit");
    /**
     * Balance.
     */
    private final ObjectProperty<BigDecimal> balance =
            new SimpleObjectProperty<>(this, "balance", new BigDecimal("0.000"));
    /**
     * Balance at store
     */
    private final ObjectProperty<BigDecimal> balanceStore =
            new SimpleObjectProperty<>(this, "balanceStore", new BigDecimal("0.000"));
    /**
     * Balance at transit.
     */
    private final ObjectProperty<BigDecimal> balanceTransit =
            new SimpleObjectProperty<>(this, "balanceTransit", new BigDecimal("0.000"));
    /**
     * Balance at point of sale.
     */
    private final ObjectProperty<BigDecimal> balanceSale =
            new SimpleObjectProperty<>(this, "balanceSale", new BigDecimal("0.000"));
    /**
     * Balance at long term store (saved).
     */
    private final ObjectProperty<BigDecimal> balanceSaved =
            new SimpleObjectProperty<>(this, "balanceSaved", new BigDecimal("0.000"));
    /**
     * Sum of input by purchase.
     */
    private final ObjectProperty<BigDecimal> inPurchase =
            new SimpleObjectProperty<>(this, "inPurchase", new BigDecimal("0.000"));
    /**
     * Sum of input by fixes.
     */
    private final ObjectProperty<BigDecimal> inFix =
            new SimpleObjectProperty<>(this, "inFix", new BigDecimal("0.000"));
    /**
     * Sum of input by returns from customers.
     */
    private final ObjectProperty<BigDecimal> inReturn =
            new SimpleObjectProperty<>(this, "inReturn", new BigDecimal("0.000"));
    /**
     * Sum of input from production line.
     */
    private final ObjectProperty<BigDecimal> inProduction =
            new SimpleObjectProperty<>(this, "inProduction", new BigDecimal("0.000"));
    /**
     * Sum of input from transfers.
     */
    private final ObjectProperty<BigDecimal> inTransfer =
            new SimpleObjectProperty<>(this, "inTransfer", new BigDecimal("0.000"));
    /**
     * Sum of output for sale.
     */
    private final ObjectProperty<BigDecimal> outSale =
            new SimpleObjectProperty<>(this, "outSale", new BigDecimal("0.000"));
    /**
     * Sum of output for wasted items.
     */
    private final ObjectProperty<BigDecimal> outWaste =
            new SimpleObjectProperty<>(this, "outWaste", new BigDecimal("0.000"));
    /**
     * Sum of output for fixing.
     */
    private final ObjectProperty<BigDecimal> outFix =
            new SimpleObjectProperty<>(this, "outFix", new BigDecimal("0.000"));
    /**
     * Sum of output for return to supplier.
     */
    private final ObjectProperty<BigDecimal> outReturn =
            new SimpleObjectProperty<>(this, "outReturn", new BigDecimal("0.000"));
    /**
     * Sum of output to production line.
     */
    private final ObjectProperty<BigDecimal> outProduction =
            new SimpleObjectProperty<>(this, "outProduction", new BigDecimal("0.000"));
    /**
     * Sum of output for transfers.
     */
    private final ObjectProperty<BigDecimal> outTransfer =
            new SimpleObjectProperty<>(this, "outTransfer", new BigDecimal("0.000"));
    /**
     * Active flag.
     */
    private final BooleanProperty active =
            new SimpleBooleanProperty(this, "active");
    /**
     * TODO: document outGift
     */
    private final ObjectProperty<BigDecimal> outGift =
            new SimpleObjectProperty<>(this, "outGift", new BigDecimal("0.000"));

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #id}.get();
     */
    public final long getId() {
        return id.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param id value to assign into {@link #id}.
     */
    public final void setId(long id) {
        this.id.set(id);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #id}.
     */
    public final LongProperty idProperty() {
        return id;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #description}.get();
     */
    public final String getDescription() {
        return description.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param description value to assign into {@link #description}.
     */
    public final void setDescription(String description) {
        this.description.set(description);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #description}.
     */
    public final StringProperty descriptionProperty() {
        return description;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #unit}.get();
     */
    public final FxUnit getUnit() {
        return unit.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param unit value to assign into {@link #unit}.
     */
    public final void setUnit(FxUnit unit) {
        this.unit.set(unit);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #unit}.
     */
    public final ObjectProperty<FxUnit> unitProperty() {
        return unit;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #balance}.get();
     */
    public final BigDecimal getBalance() {
        return balance.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param balance value to assign into {@link #balance}.
     */
    public final void setBalance(BigDecimal balance) {
        this.balance.set(balance);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #balance}.
     */
    public final ObjectProperty<BigDecimal> balanceProperty() {
        return balance;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #balanceStore}.get();
     */
    public final BigDecimal getBalanceStore() {
        return balanceStore.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param balanceStore value to assign into {@link #balanceStore}.
     */
    public final void setBalanceStore(BigDecimal balanceStore) {
        this.balanceStore.set(balanceStore);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #balanceStore}.
     */
    public final ObjectProperty<BigDecimal> balanceStoreProperty() {
        return balanceStore;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #balanceTransit}.get();
     */
    public final BigDecimal getBalanceTransit() {
        return balanceTransit.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param balanceTransit value to assign into {@link #balanceTransit}.
     */
    public final void setBalanceTransit(BigDecimal balanceTransit) {
        this.balanceTransit.set(balanceTransit);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #balanceTransit}.
     */
    public final ObjectProperty<BigDecimal> balanceTransitProperty() {
        return balanceTransit;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #balanceSale}.get();
     */
    public final BigDecimal getBalanceSale() {
        return balanceSale.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param balanceSale value to assign into {@link #balanceSale}.
     */
    public final void setBalanceSale(BigDecimal balanceSale) {
        this.balanceSale.set(balanceSale);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #balanceSale}.
     */
    public final ObjectProperty<BigDecimal> balanceSaleProperty() {
        return balanceSale;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #balanceSaved}.get();
     */
    public final BigDecimal getBalanceSaved() {
        return balanceSaved.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param balanceSaved value to assign into {@link #balanceSaved}.
     */
    public final void setBalanceSaved(BigDecimal balanceSaved) {
        this.balanceSaved.set(balanceSaved);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #balanceSaved}.
     */
    public final ObjectProperty<BigDecimal> balanceSavedProperty() {
        return balanceSaved;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #inPurchase}.get();
     */
    public final BigDecimal getInPurchase() {
        return inPurchase.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param inPurchase value to assign into {@link #inPurchase}.
     */
    public final void setInPurchase(BigDecimal inPurchase) {
        this.inPurchase.set(inPurchase);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #inPurchase}.
     */
    public final ObjectProperty<BigDecimal> inPurchaseProperty() {
        return inPurchase;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #inFix}.get();
     */
    public final BigDecimal getInFix() {
        return inFix.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param inFix value to assign into {@link #inFix}.
     */
    public final void setInFix(BigDecimal inFix) {
        this.inFix.set(inFix);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #inFix}.
     */
    public final ObjectProperty<BigDecimal> inFixProperty() {
        return inFix;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #inReturn}.get();
     */
    public final BigDecimal getInReturn() {
        return inReturn.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param inReturn value to assign into {@link #inReturn}.
     */
    public final void setInReturn(BigDecimal inReturn) {
        this.inReturn.set(inReturn);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #inReturn}.
     */
    public final ObjectProperty<BigDecimal> inReturnProperty() {
        return inReturn;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #inProduction}.get();
     */
    public final BigDecimal getInProduction() {
        return inProduction.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param inProduction value to assign into {@link #inProduction}.
     */
    public final void setInProduction(BigDecimal inProduction) {
        this.inProduction.set(inProduction);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #inProduction}.
     */
    public final ObjectProperty<BigDecimal> inProductionProperty() {
        return inProduction;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #inTransfer}.get();
     */
    public final BigDecimal getInTransfer() {
        return inTransfer.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param inTransfer value to assign into {@link #inTransfer}.
     */
    public final void setInTransfer(BigDecimal inTransfer) {
        this.inTransfer.set(inTransfer);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #inTransfer}.
     */
    public final ObjectProperty<BigDecimal> inTransferProperty() {
        return inTransfer;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outSale}.get();
     */
    public final BigDecimal getOutSale() {
        return outSale.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outSale value to assign into {@link #outSale}.
     */
    public final void setOutSale(BigDecimal outSale) {
        this.outSale.set(outSale);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outSale}.
     */
    public final ObjectProperty<BigDecimal> outSaleProperty() {
        return outSale;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outWaste}.get();
     */
    public final BigDecimal getOutWaste() {
        return outWaste.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outWaste value to assign into {@link #outWaste}.
     */
    public final void setOutWaste(BigDecimal outWaste) {
        this.outWaste.set(outWaste);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outWaste}.
     */
    public final ObjectProperty<BigDecimal> outWasteProperty() {
        return outWaste;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outFix}.get();
     */
    public final BigDecimal getOutFix() {
        return outFix.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outFix value to assign into {@link #outFix}.
     */
    public final void setOutFix(BigDecimal outFix) {
        this.outFix.set(outFix);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outFix}.
     */
    public final ObjectProperty<BigDecimal> outFixProperty() {
        return outFix;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outReturn}.get();
     */
    public final BigDecimal getOutReturn() {
        return outReturn.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outReturn value to assign into {@link #outReturn}.
     */
    public final void setOutReturn(BigDecimal outReturn) {
        this.outReturn.set(outReturn);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outReturn}.
     */
    public final ObjectProperty<BigDecimal> outReturnProperty() {
        return outReturn;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outProduction}.get();
     */
    public final BigDecimal getOutProduction() {
        return outProduction.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outProduction value to assign into {@link #outProduction}.
     */
    public final void setOutProduction(BigDecimal outProduction) {
        this.outProduction.set(outProduction);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outProduction}.
     */
    public final ObjectProperty<BigDecimal> outProductionProperty() {
        return outProduction;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outTransfer}.get();
     */
    public final BigDecimal getOutTransfer() {
        return outTransfer.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outTransfer value to assign into {@link #outTransfer}.
     */
    public final void setOutTransfer(BigDecimal outTransfer) {
        this.outTransfer.set(outTransfer);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outTransfer}.
     */
    public final ObjectProperty<BigDecimal> outTransferProperty() {
        return outTransfer;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #outGift}.get();
     */
    public final BigDecimal getOutGift() {
        return outGift.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param outGift value to assign into {@link #outGift}.
     */
    public final void setOutGift(BigDecimal outGift) {
        this.outGift.set(outGift);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #outGift}.
     */
    public final ObjectProperty<BigDecimal> outGiftProperty() {
        return outGift;
    }

    /**
     * FX Accessor - getter.
     *
     * @return value of {@link #active}.get();
     */
    public final boolean isActive() {
        return active.get();
    }

    /**
     * FX Accessor - setter.
     *
     * @param active value to assign into {@link #active}.
     */
    public final void setActive(boolean active) {
        this.active.set(active);
    }

    /**
     * FX Accessor - property.
     *
     * @return property {@link #active}.
     */
    public final BooleanProperty activeProperty() {
        return active;
    }

    @Override
    public boolean equals(Object o) {
        return this == o || o instanceof FxItem fxItem &&
                getId() == fxItem.getId();
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
